### PR TITLE
fix h2 norm

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Ah yes, thanks!

**Comment by tjhei** [comment]
Did you check that the formula looks good? I will make a PR for deal.II integrate_difference() to include the h2 seminorm at some point then.

**Comment by bangerth** [comment]
No, I didn't check -- I assumed you were doing the right thing and that it fixed the odd convergence rates I was seeing :-)

`intergate_difference()` -- no, it's not right. It's not actually the h2 seminorm as it stands; one would need to add gradient jump terms to make an norm equivalent to the h2 seminorm. What we have here is really just the "broken H2 seminorm", but that's not an equivalent norm.

**Comment by tjhei** [comment]
> `intergate_difference()` -- no, it's not right. It's not actually the h2 seminorm as it stands;

well, one could call it "broken_h2_seminorm" ?

**Comment by bangerth** [comment]
On 11/7/19 12:38 PM, Timo Heister wrote:
> well, one could call it "broken_h2_seminorm" ?

Yes, maybe. It's not particularly meaningful, though.

**Pull request merged**
